// React/dog-app/src/App.js
import { useState, useEffect } from 'react';
import './App.css';
import Header from './components/Header';
import SearchBar from './components/SearchBar';
import DogDetails from './components/DogDetails';

function App() {
  const [dogs, setDogs] = useState([]);
  const [randomDogs, setRandomDogs] = useState([]);

  const fetchDogs = async (url) => {
      const result = await fetch(url);

      const data = await result.json();
      
      return data;
  }

  useEffect(() => {
    const getRandomDogs = async () => {
      const dogs = await fetchDogs('https://api.thedogapi.com/v1/images/search?limit=12');

      setRandomDogs(dogs);
      setDogs(dogs);
    }

    getRandomDogs();
  }, []);

  useEffect(() => {
    
  }, [dogs]);

  return (
    <div className="container">
      <Header />
      <SearchBar setDogs={setDogs} randomDogs={randomDogs} fetchDogs={fetchDogs} />
      <DogDetails dogs={dogs} />
    </div>
  );
}

export default App;

// Svelte/src/App.svelte
<script>
	import { onMount } from 'svelte';

	import Header from './components/Header.svelte';
	import SearchBar from './components/SearchBar.svelte';
	import DogDetails from './components/DogDetails.svelte';

	let dogs = [];
	let randomDogs = [];

	const fetchDogs = async (url) => {
		const result = await fetch(url);

		const data = await result.json();
		
		return data;
	}

	onMount(async () => {
		randomDogs = await fetchDogs('https://api.thedogapi.com/v1/images/search?limit=12');

		dogs = randomDogs;
	});
</script>

<div class="container">
	<Header />
	<SearchBar />
	<DogDetails dogs={dogs} />
</div>

<style>
	.container {
		width: 80%;
		margin: 0 auto;
	}
</style>
